---
name: "auto-release"

on:
  push:
    branches:
      - "master"
      
  workflow_dispatch:

jobs:
  auto-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Auto Release"
        run: |
          echo "Done!"
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto Release"
          files: |
            JJS Airline.lua
            JJS Taxi.lua
            JJS Translator.lua
            JJS Pet.lua
            JJS Avenger Utils.lua
            


