---
name: "auto-release"

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  auto-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Delete tag and release
        id: delete_release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Auto Release"
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            ./Airline Script/JJS Airline.lua
            ./Taxi Script/JJS Taxi.lua
            ./Translator/JJS Translator.lua
            ./Pet/JJS Pet.lua
            ./Avenger utils/JJS Avenger Utils.lua
            ./Airtaxi Script/JJS Airtaxi.lua



