---
name: "auto-release"

on:
  push:
    branches:
      - "master"

  workflow_dispatch:

jobs:
  pre-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Auto Release"
        run: |
          echo "Done!"
        
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto Release"
          files: |
            README.md
            


